name = "rorplanner-graphql-proxy"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Set these after creating a custom domain for the worker
workers_dev = true

# uncomment to bind a custom route (after adding your zone)
# routes = [ { pattern = "proxy.example.com/graphql", custom_domain = true } ]
name = "rorplanner-proxy"
main = "src/index.ts"
compatibility_date = "2024-12-01"
workers_dev = true
routes = []
