name: Deploy Cloudflare Worker (GraphQL Proxy)

on:
  push:
    branches: [ master ]
    paths:
      - 'cf-worker/**'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cf-worker
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: cf-worker
          command: publish
